[project]
name = "sqliac"
version = "0.1.0"
description = "An alternative to Terraform for SQL databases without using a state."
readme = "README.md"
requires-python = ">=3.14"
license = { file = "LICENSE" }
authors = [
  { name = "Ruslan Gonzalez Konstantinov", email = "rus.kgo.gmail@example.com" },
]
keywords = ["sql", "iac", "terraform-alternative", "database"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Database",
]
dependencies = [
    "Jinja2",
    "rich",
    "sqlparse",
    "dictdiffer",
]
[project.urls]
Homepage = "https://codeberg.org/ruskgo/sqliac"
"Bug Tracker" = "https://codeberg.org/ruskgo/sqliac/issues"

[project.optional-dependencies]
dev = ["pytest>=9.1.1"]
snowflake = ["sqliac-snowflake"]

[tool.uv.workspace]
  members = ["sqliac_adapters/sqliac_snowflake"]

[project.entry-points."sqliac.adapters"]
snowflake = "adapter:SnowflakeAdapter"

[tool.uv.sources]
sqliac-snowflake = { workspace = true }

[project.scripts]
sqliac = "sqliac.cli:main"

[tool.setuptools.package-data]
sqliac = ["templates/**/*.toml", "templates/**/*.sql"]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
