[project]
name = "sqliac"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "Jinja2",
    "rich",
    "sqlparse",
    "dictdiffer",
    "icecream>=2.2.0",
]

[project.optional-dependencies]
snowflake = ["snowflake-connector-python[secure-local-storage]", "cryptography"]

[project.scripts]
sqliac = "sqliac.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
