[snowflake.database.ddl_command]
create = "CREATE OR ALTER"
alter  = "CREATE OR ALTER"
drop   = "DROP"

[snowflake.database.ddl_context]
name = "MODELING"
transient = false
data_retention_time_in_days = 1
max_data_extension_time_in_days = 15
default_ddl_collation = "utf8"
log_level = "INFO"
wait_time = 0

[snowflake.database.ddl_context.depends_on]


[snowflake.schema.ddl_command]
create = "CREATE OR ALTER"
alter  = "CREATE OR ALTER"
drop   = "DROP"

[snowflake.schema.ddl_context]
name = "MODELING.MODELING_SCHEMA"
transient = false
managed_access = false
data_retention_time_in_days = 1
comment = "Example schema"
wait_time = 0

[snowflake.schema.ddl_context.depends_on]


[snowflake.table.ddl_command]
create = "CREATE"
alter  = "ALTER"
drop   = "DROP"

[snowflake.table.ddl_context]
name = "MODELING.MODELING_SCHEMA.FIRST_TABLE"
wait_time = 0

[[snowflake.table.ddl_context.columns]]
name = "first_column"
type = "NUMBER(38,0)"
nullable = "yes"
comment = "Primary key"

[[snowflake.table.ddl_context.columns]]
name = "second_column"
type = "VARCHAR(100)"
nullable = "no"
comment = "Name field"

[snowflake.table.ddl_context.depends_on]
database = [
  "example_database"
]
