[project]
name = "sqliac-snowflake"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "sqliac>=0.1.0",
  "snowflake-connector-python[secure-local-storage]",
  "cryptography",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."sqliac.adapters"]
snowflake = "sqliac_snowflake.adapter:SnowflakeAdapter"

[tool.uv.sources]
sqliac = { workspace = true }

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
