database:
- name: my_db
  transient: false
  data_retention_time_in_days: 1
  max_data_extension_time_in_days:
  trace_level: null
  log_level: null
  comment: null
  depends_on: 
    database_role:
    - my_db_role
  object_id_tag: 792c2a9c-2812-39ed-99b4-1c182450260f
