database:
- name: my_db
  transient: false
  owner: ACCOUNTADMIN
  data_retention_time_in_days: 1
  max_data_extension_time_in_days:
  default_ddl_collation: utf8
  trace_level: null
  log_level: INFO
  comment: null
  depends_on: 
    database_role:
    - my_db_role
  wait_time:
  object_id_tag: 792c2a9c-2812-39ed-99b4-1c182450260f
- name:
  transient:
  owner: ACCOUNTADMIN
  data_retention_time_in_days: 
  max_data_extension_time_in_days:
  default_ddl_collation: utf8
  trace_level: null
  log_level:
  comment: null
  depends_on: 
  wait_time:
  object_id_tag: 