views:
  - name: db.shema.some_view
    owner: SYSADMIN
    secure: true
    volatile: false
    recursive: false
    change_tracking: false
    copy_grants: false
    comment: ""
    wait_time:
    object_id_tag:
    as_: |
      select * from table