[[table]]
name = "MODELING.MODELING_SCHEMA.FIRST_TABLE"
wait_time = 0
[table.depends_on]
database = ["MODELING"]
schema = ["MODELING.MODELING_SCHEMA"]

[[table.columns]]
name = "column1"
type = "varchar"
nullable = 'NO'
comment = "Column 1 description"

[[table.columns]]
name = "column2"
type = "NUMBER"
comment = "Column 2 description"

[[table.columns]]
name = "column3"
type = "varchar"
comment = "Column 3 description"

[[table.columns]]
name = "column4"
type = "varchar"
comment = "Column 4 description"

[[table]]
name = "PRESENTATION.EXAMPLE_SCHEMA.SECOND_TABLE"
wait_time = 0
[[table.columns]]
name = "column1"
type = "NUMBER"
comment = "Column 1 description"
[[table.columns]]
name = "column2"
type = "NUMBER"
comment = "Column 2 description"
[[table.columns]]
name = "column3"
type = "NUMBER"
comment = "Column 3 description"
[table.depends_on]
database = ["MODELING", "PRESENTATION"]
schema = ["PRESENTATION.EXAMPLE_SCHEMA"]
